### ISSUE TITLE
你好啊

### ISSUE THREAD

**Issue by xQ628** [wanqqq29/cuddly-meme#3]
up，请问这个项目需要授权其它东西才能运行吗

**Comment by wanqqq29** [comment]
不需要 配好django和npm 就可以

**Comment by xQ628** [comment]
up，请问这个是研究生毕设论文吗（看着好像是论文作者），我这本科生做毕设弄这种是不是没必要呢

**Comment by wanqqq29** [comment]
项目是本科毕设。选题主要看学校要求，是否必须机器学习方面的
